version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: municipios-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_KEY="
      - "APP_URL=http://localhost:8000"
      - "DB_CONNECTION=sqlite"
      - "MUNICIPIOS_PROVIDER=ibge"
      - "MUNICIPIOS_VERIFY_SSL=true"
      - "FRONTEND_URL=http://localhost:3000"
    ports:
      - "8000:8000"
    networks:
      - municipios-network

  frontend:
    container_name: municipios-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - app
    networks:
      - municipios-network

  redis:
    image: redis:alpine
    container_name: municipios-api-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - municipios-network

networks:
  municipios-network:
    driver: bridge

volumes:
  redisdata:
    driver: local
