version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: municipios-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/conf.d/php.ini:/usr/local/etc/php/conf.d/app.ini
    environment:
      - "APP_ENV=local"
      - "APP_DEBUG=true"
      - "APP_KEY="
      - "APP_URL=http://localhost:8000"
      
      - "DB_CONNECTION=mysql"
      - "DB_HOST=db"
      - "DB_PORT=3306"
      - "DB_DATABASE=${DB_DATABASE:-municipios}"
      - "DB_USERNAME=${DB_USERNAME:-laravel}"
      - "DB_PASSWORD=${DB_PASSWORD:-secret}"
      
      - "MUNICIPIOS_PROVIDER=ibge"
      - "MUNICIPIOS_VERIFY_SSL=true"
    depends_on:
      - db
    networks:
      - municipios-network

  db:
    image: mysql:8.0
    container_name: municipios-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-municipios}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT:-3306}:3306"
    networks:
      - municipios-network

  nginx:
    image: nginx:alpine
    container_name: municipios-api-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
    networks:
      - municipios-network

  redis:
    image: redis:alpine
    container_name: municipios-api-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redisdata:/data
    networks:
      - municipios-network

networks:
  municipios-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  redisdata:
    driver: local
